# source : https://github.com/Georgetown-IR-Lab/query-clarification-data/blob/master/queries-and-questions.txt
MED_QUERIES = [
    "indigestion",
    "dropsy disease",
    "profuse sweating",
    "suicidal thoughts",
    "slow heart rate",
    "graves disease",
    "excessive burping",
    "how to lose weight",
    "hair loss in women causes",
    "fear of heights",
    "leg blood clot symptoms",
    "can't sleep",
    "hairloss",
    "difficulty breathing",
    "body odor",
    "salivary gland stones",
    "excessive sweating",
    "nervousness",
    "sunlight causing hives",
    "foods to avoid with acid reflux",
    "trouble swallowing when eating",
    "how to stop a nosebleed",
    "hives",
    "common cold symptoms",
    "stress incontinence",
    "sweating sickness",
    "bloated stomach",
    "blood clot",
    "sweet sweat",
    "kidney failure symptoms",
    "trouble swallowing",
    "heat stroke",
    "spontaneous abortion",
    "foods cause gout",
    "bloody stools in adults",
    "back problems",
    "indigestion symptoms",
    "shaking hands",
    "ringing ears",
    "memory loss",
    "nosebleed",
    "brown vaginal discharge",
    "memory loss in women",
    "pressure ulcers",
    "acid reflux symptoms",
    "what causes hair loss in women",
    "erectile dysfunction remedies",
    "tooth ache",
    "acid reflux",
    "double vision causes"
]