node collect.js allDevices duckduckgo covid19 covid19_0
node collect.js allDevices duckduckgo trend trend_1
node collect.js allDevices duckduckgo trend trend_2
node collect.js allDevices duckduckgo trend trend_3
node collect.js allDevices duckduckgo trend trend_4
node collect.js allDevices duckduckgo trend trend_5
node collect.js allDevices duckduckgo trend trend_6
node collect.js allDevices duckduckgo trend trend_7
node collect.js allDevices duckduckgo trend trend_8
node collect.js allDevices duckduckgo trend trend_9
node collect.js allDevices duckduckgo trend trend_10
node collect.js allDevices duckduckgo trend trend_11
node collect.js allDevices duckduckgo top top_0
node collect.js allDevices duckduckgo top top_1
node collect.js allDevices duckduckgo top top_2
node collect.js allDevices duckduckgo top top_3
node collect.js allDevices duckduckgo med med_0
node collect.js allDevices duckduckgo med med_1