node collect.js allDevices google covid19 covid19_0
node collect.js allDevices google trend trend_1
node collect.js allDevices google trend trend_2
node collect.js allDevices google trend trend_3
node collect.js allDevices google trend trend_4
node collect.js allDevices google trend trend_5
node collect.js allDevices google trend trend_6
node collect.js allDevices google trend trend_7
node collect.js allDevices google trend trend_8
node collect.js allDevices google trend trend_9
node collect.js allDevices google trend trend_10
node collect.js allDevices google trend trend_11
node collect.js allDevices google top top_0
node collect.js allDevices google top top_1
node collect.js allDevices google top top_2
node collect.js allDevices google top top_3
node collect.js allDevices google med med_0
node collect.js allDevices google med med_1